version: '3.9'

networks:
  backend:

services:

  php:
    image: yiisoftware/yii2-php:8.1-apache
    container_name: serm
    depends_on:
      - "db"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - 8010:80
    networks:
      - backend

  db:
    image: mariadb:10.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - 33306:3306
    volumes:
      - ./src/mysql/db:/var/lib/mysql
      - ./src/mysql/logs:/var/log/mysql
      - ./src/mysql/mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend
